name: simulated_delivery_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.5.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_polyline_points: ^2.0.0
  geolocator: ^10.0.0
  dartz: ^0.10.1
  dio: ^5.3.2
  get_it: ^7.6.2
  fluttertoast: ^8.2.2
  sliding_sheet: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.3

flutter:

  uses-material-design: true

  # assets:
  #   - assets/images/


